
myUploadPath: d:/c76_blog/

server:
   port: 80
   
   
   
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1/S3-Pchx-blog
      username: root
      password: a
      driverClassName: com.mysql.jdbc.Driver
   
  
   

#静态资源映射
   resource:
      staticLocations:
         - classpath:/resource/   
         - classpath:/static/
         - file:${myUploadPath}
#文件上传大小配置
   servlet:
      multipart:
         maxFileSize: 1000000000      
         
   mail:
    #邮箱服务地址
      host: smtp.qq.com
    #用户名
      username: 1426473251@qq.com
    # 密码
      password: iuisplezlrnejgci
    
    #字符集编码
      default-encoding: UTF-8
         
#   mvc:
#      view:
#         prefix: WEB-INF/jsp/
#         suffix: .jsp
   
mail: 
  fromMail:
    addr: 1426473251@qq.com  
      
mybatis:
   #实体类路径
   type-aliases-package: com.yc.blog.bean
   configuration:
      mapUnderscoreToCamelCase: true
   
logging:
  level:
    com:
       yc:
          blog:
             dao: debug
             web: warn
         